"""Initial schema including item module

Revision ID: 770d28c796af
Revises: 
Create Date: 2026-02-16 20:29:41.796244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '770d28c796af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_gid', sa.String(length=255), nullable=False),
    sa.Column('item_xid', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('otm_sync_status', sa.String(length=20), nullable=False),
    sa.Column('otm_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name', 'item_xid', name='uq_domain_xid'),
    sa.UniqueConstraint('item_gid', name='uq_item_gid')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_item_sync_status', ['otm_sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_domain_name'), ['domain_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_gid'), ['item_gid'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_xid'), ['item_xid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_item_xid'))
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_gid'))
        batch_op.drop_index(batch_op.f('ix_items_domain_name'))
        batch_op.drop_index('ix_item_sync_status')

    op.drop_table('items')
    op.drop_table('field_configs')
    # ### end Alembic commands ###
